### ISSUE TITLE
ActiveState project integration?

### ISSUE THREAD

**Issue by shnewto** [trekhleb/learn-python#11]
👋This is a **great** project! Thank you for all the work you've put into it!

I'd be interested in contributing a configuration file and some docs for it (as an option in or near the Prerequisites section your README.md) to your project but wanted to run it by you with context before just making a PR. 

At the hack night meetups I've been going to, a lot of the people showing up want to learn Python but don't know where to start (or even where to look). But _this_ is the perfect place to start, and to continue revisiting! 💯 💯 

One thing we consistently run into though is getting up and running in the first place. Learning environments are extra tricky to navigate on those nights because during experimentation people have often ended up with different Python and Python package versions installed globally / locally / with pip / with apt-get, etc.

I think offering integration with an ActiveState project could be really helpful for people with difficulty getting started _and_ people like me trying to help out on hack nights.

Here's the documentation addition I'm imagining:

---

On Linux and have ActiveState's [state tool](http://docs.activestate.com/platform/start/state.html)?

Run `state activate` from the project directory

---

And here's what the config file looks like as an `activestate.yaml`:
```
name: learn-python
owner: shnewto
languages:
- name: python
```

The general idea is that with an account on https://platform.activestate.com/ you can preconfigure a Python (or Perl) environment with whatever packages you want and it builds a binary you can install. The state tool works as a kind of a "meta venv" for those preconfigured environments so you don't have to install your project's dependencies system wide (Windows and macOS support on the way).

Here's a link to the `learn-python` project I created https://platform.activestate.com/shnewto/learn-python
(it does require creating an account to view while we're in the early stages of building all this up 🙃) 

Would be happy to answer any questions or to make a PR if you're open to it!

P.S. If you'd rather create your own project as and use that instead of the `shnewto/learn-python` project I put together that'd be great too! If you did the configuration file might look something like this:
```
name: learn-python
owner: trekhleb
languages:
- name: python
```

**Comment by shnewto** [comment]
Btw, for the sake of clearly stated transparency, I work on https://platform.activestate.com at ActiveState.

**Comment by Kartik-Khandelwal** [comment]
Sir, is there anything I can do for you.

**Comment by shnewto** [comment]
🤔 I'd sort of forgotten about this, I'm no longer with ActiveState so I think I'll just close this ticket. Activestate does maintain a fork though so if anyone's curious about a potential contribution from them that'd be a good place to reach out.
