### ISSUE TITLE
Translation request

### ISSUE THREAD

**Issue by JoseDeFreitas** [trekhleb/learn-python#30]
Hello 👋.
I've found this project and thought it is quite cool. The examples in it are very helpful. Because of that, I'd want to translate the [README file](https://github.com/trekhleb/learn-python/blob/master/README.md) into Spanish (the same way as the Portuguese translation: in the root directory and in a file called `README.es`). As I see there's a translation into Portuguese, I thought maybe a translation into Spanish would also be good. I'm a native Spanish speaker who has previously contributed to open-source projects and repositories.
I'm opening this issue to let you know about this and receive a response from you: if you're interested, tell me so I can work on it. If not, you can close this issue.
Thank you in advance!

**Comment by gez-hub** [comment]
Good

**Comment by JoseDeFreitas** [comment]
Closing in order to clean this up as I've already sent the pull request (see above).
