### ISSUE TITLE
Can I use this code for online lecture?

### ISSUE THREAD

**Issue by godaji** [trekhleb/learn-python#53]
Hello. Thanks for releasing a good open source.
I'm Korean and I'm trying to teach Python online in Korea.
Would it be ok to use the code here as an example?
It's for commercial purposes. It's under the MIT license, but I think it's better to ask.

**Comment by lebogang-a11y** [comment]
Yes, I'll like to know more about python app
Does it deals with hacking ?

**Comment by godaji** [comment]
Thank you for your permission.
We are preparing a lecture on MLOps.
I am trying to teach python as a basic subject to students.

**Comment by trekhleb** [comment]
@godaji please feel free to re-use this code in your lectures with the back-link to this project.
