### ISSUE TITLE
Usage of this project to another project as a template

### ISSUE THREAD

**Issue by FahimFBA** [trekhleb/learn-python#55]
Hello, I am planning to create a project as learn-julia containing every basic of Julia programming language. I was searching for a project which I can use as a template and follow the sequences. This project seems like an ideal one to me. Can I use this project structure and everything as a template and for following the sequence for my own project?

Please do let me know.

**Comment by trekhleb** [comment]
@FahimFBA sure, you may re-use the structure. Good luck with your new learn-julia project 👍🏻
