### ISSUE TITLE
how did you get sick of your Ukraine

### ISSUE THREAD

**Issue by jora535** [trekhleb/learn-python#64]
Вы лживые лицемеры думаю наша армия даст вам всем проспаться поганым фашистам

**Comment by carlchencup** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，邮件以收到，我会尽快给您回复。

**Comment by oleksandr17** [comment]
@jora535 Жора, научись запятые ставить в нужном месте.
Фашисты в вашей всратой расии!
Чмошник! 🖕
